apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tm67p0jax-go 
  janus-idp.io/tekton: tm67p0jax-go
  backstage.io/kubernetes-id: tm67p0jax-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tm67p0jax-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml