apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tm67p0jax-go-gitops
  description: This is GitOps manifest for tm67p0jax-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=tm67p0jax-go
    backstage.io/kubernetes-id: tm67p0jax-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tm67p0jax-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tm67p0jax-go
